- src/main/java/org/tealeaf/javamarkdown/MarkdownWriter.java
- src/main/java/org/tealeaf/javamarkdown/elements/Header.java
- src/main/java/org/tealeaf/javamarkdown/exceptions/IllegalHeaderLevelException.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownWriterTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/HeaderTest.java
- src/test/java/test/Tests.java
> Added Header Element

- src/main/java/org/tealeaf/javamarkdown/lists/BulletList.java
- src/test/java/org/tealeaf/javamarkdown/list/BulletListTest.java
- src/test/java/org/tealeaf/javamarkdown/list/NumberedListTest.java
> Added all unit test for bulletList

- .idea/misc.xml
- src/main/java/org/tealeaf/javamarkdown/MarkdownElement.java
- src/main/java/org/tealeaf/javamarkdown/MarkdownWriter.java
- src/main/java/org/tealeaf/javamarkdown/elements/Bold.java
- src/main/java/org/tealeaf/javamarkdown/types/InlineElement.java
- src/main/java/org/tealeaf/javamarkdown/types/ListStructure.java
- src/main/java/org/tealeaf/javamarkdown/types/Structure.java
As well as additional changes to javadoc formatting for checkType
> Added Javadocs for Bold

- src/main/java/org/tealeaf/javamarkdown/elements/Image.java
- src/test/java/org/tealeaf/javamarkdown/elements/ImageTest.java
Added the `new Image(src)` constructor that does not include any content
> Added simple image constructor

- src/main/java/org/tealeaf/javamarkdown/elements/Link.java
- src/test/java/org/tealeaf/javamarkdown/elements/LinkTest.java
Added link constructor where the content is the same as the url (`new Link(url)`)
> Added simple link constructor

- .github/CODEOWNERS
Files added under @LittleTealeaf 
```
README.md
CONTRIBUTING.md
CODE_OF_CONDUCT.md
SECURITY.md
LICENSE
.gitignore
```
> Added various files to CODEOWNERS

- src/main/java/org/tealeaf/javamarkdown/MarkdownBuffer.java
- src/main/java/org/tealeaf/javamarkdown/MarkdownCompiler.java
- src/main/java/org/tealeaf/javamarkdown/MarkdownWriter.java
- src/main/java/org/tealeaf/javamarkdown/elements/CodeBlock.java
- src/main/java/org/tealeaf/javamarkdown/elements/Link.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownBufferTest.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownCompilerTest.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownWriterTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/BulletListTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/CodeBlockTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/CodeTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/LinkTest.java
The primary goal of this pull request is to implement the MarkdownBuffer. However, to standardize the project, a lot of minor changes will be made. 
Firstly, the implementation of `MarkdownCompiler` brings about a "standardizing" of methods within `MarkdownWriter` and `MarkdownBuffer`. I am open to name suggestions instead of `MarkdownCompiler`.
Secondly, this will require many minor changes to the other classes. I will try and make them separate pull requests but some have slipped into this one.
> Created `MarkdownBuffer` and standardized append methods

- src/main/java/org/tealeaf/javamarkdown/types/ListStructure.java
- src/test/java/org/tealeaf/javamarkdown/elements/BulletListTest.java
- src/test/java/org/tealeaf/javamarkdown/elements/NumberedListTest.java
- src/test/java/org/tealeaf/javamarkdown/types/ListStructureTest.java
> Added Stream and List support in Lists

- .github/workflows/gradle.yml
Use gradle-build-action cache instead of setup-java cache
> Change tests cache source

- .github/labeler.yml
- .github/python/release.py
- .github/workflows/pullrequest.yml
This makes PRs that change something in the .github folder easier to notice
> Added auto-labeler to PRs

- .github/workflows/release.yml
This prevents bad code from somehow ending up in a full release
> Test Codes before Releases

- .github/labeler.yml
- .github/workflows/pullrequest.yml
Multiple commits will probably be made here to attempt to resolve the problem
> Updated labeler.yml

- src/main/java/org/tealeaf/javamarkdown/elements/Header.java
Manually used char arrays instead of string concatenation
> Optimized Header asString() method

- src/main/java/org/tealeaf/javamarkdown/MarkdownBuffer.java
- src/main/java/org/tealeaf/javamarkdown/elements/Bold.java
- src/main/java/org/tealeaf/javamarkdown/elements/BulletList.java
- src/main/java/org/tealeaf/javamarkdown/elements/Header.java
- src/main/java/org/tealeaf/javamarkdown/types/InlineElement.java
- src/main/java/org/tealeaf/javamarkdown/types/Markup.java
Not all are completely correct, but at least some of the documentation is good
> Added some missing since tags

- src/main/java/org/tealeaf/javamarkdown/elements/Header.java
- src/main/java/org/tealeaf/javamarkdown/types/Markup.java
> Add Documentation to Optimized asString() methods

- src/test/java/org/tealeaf/javamarkdown/types/ListStructureTest.java
> Add Missing Tests for `ListStructure`

- src/main/java/org/tealeaf/javamarkdown/elements/Strikethrough.java
> Javadocs: `Strikethrough`

- src/main/java/org/tealeaf/javamarkdown/elements/Italic.java
> Javadocs: `Italic`

- src/main/java/org/tealeaf/javamarkdown/MarkdownBuffer.java
> Javadocs: `MarkdownBuffer`

- src/main/java/org/tealeaf/javamarkdown/MarkdownWriter.java
- src/main/java/org/tealeaf/javamarkdown/types/Markup.java
> Remove Commented Code in `Markup.java` and `MarkdownWriter`

- src/main/java/org/tealeaf/javamarkdown/elements/Image.java
> Javadocs: `Image`

- src/main/java/org/tealeaf/javamarkdown/elements/Link.java
> Optimize Link `asString()`

- src/main/java/org/tealeaf/javamarkdown/elements/CodeBlock.java
- src/main/java/org/tealeaf/javamarkdown/elements/Header.java
- src/main/java/org/tealeaf/javamarkdown/elements/Table.java
- src/main/java/org/tealeaf/javamarkdown/types/Structure.java
> Specify `requiresNewlineBefore` and `requiresNewlineAfter` in `Structure.java`

- src/main/java/org/tealeaf/javamarkdown/elements/Link.java
- src/main/java/org/tealeaf/javamarkdown/types/InlineElement.java
- src/main/java/org/tealeaf/javamarkdown/types/Markup.java
> Specify `requiresNewLineBefore` and `requiresNewLineAfter` in `InlineElement.java`

- src/main/java/org/tealeaf/javamarkdown/types/ListStructure.java
> Javadocs: `ListStructure`

- src/main/java/org/tealeaf/javamarkdown/elements/Link.java
- src/test/java/org/tealeaf/javamarkdown/elements/LinkTest.java
> Allow passing images as contents of links

- src/main/java/org/tealeaf/javamarkdown/types/InlineElement.java
> Fix Javadoc Wording in `InlineElement`

- src/main/java/org/tealeaf/javamarkdown/types/InlineElement.java
> Added Javadoc to `InlineElement`

- src/main/java/org/tealeaf/javamarkdown/elements/Table.java
> Made alignment variable private in Table.Alignment

- src/main/java/org/tealeaf/javamarkdown/elements/Table.java
> Javadoc: `Table.Alignment` individual values

- src/main/java/org/tealeaf/javamarkdown/MarkdownElement.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownElementTest.java
> Added `asString(boolean)` method to handle newlines

- src/main/java/org/tealeaf/javamarkdown/MarkdownElement.java
- src/test/java/org/tealeaf/javamarkdown/MarkdownElementTest.java
> Add `toAppendable()` to `MarkdownElement`

- src/main/java/org/tealeaf/javamarkdown/MarkdownElement.java
> Removed `See` tags from `MarkdownElement`

- src/main/java/org/tealeaf/javamarkdown/MarkdownElement.java
> Fix Typo in `MarkdownElement`

- src/main/java/org/tealeaf/javamarkdown/elements/Image.java
> Fix typo in `Image.asString()`

- src/main/java/org/tealeaf/javamarkdown/MarkdownWriter.java
> Optimize `MarkdownWriter.appendMarkdownElement()`
